version: '3.8'

services:
  alchemy:
    image: ${ALCHEMY_IMAGE}
    container_name: alchemy
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 5077:5077

networks:
  default:
    external:
      name: thenewsquest-network
