version: '3.8'

services:
  alchemy:
    image: bietdoikiem/alchemy-chapter:1.0
    container_name: alchemy-chapter
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - FLASK_APP=api_gateway.py
      - FLASK_ENV=development
    ports:
      - 5177:5000

networks:
  default:
    external:
      name: thenewsquest-network
